export const GET_VIDEOS = 'GET_VIDEOS';
export const ADD_VIDEO = 'ADD_VIDEO';
export const DELETE_VIDEO = 'DELETE_VIDEO';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_VIDEO = 'UPDATE_VIDEO';
export const CLEAR_VIDEOS = 'CLEAR_VIDEOS';
export const SET_LOADING = 'SET_LOADING';
export const VIDEOS_ERROR = 'VIDEOS_ERROR';
export const SEARCH_VIDEOS = 'SEARCH_VIDEOS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';